version: "3.8"

services:

  kafka1:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster-01
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:19092
    ports: ["19092:9092"]
